// This file is automatically generated by qtc from "view.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line view.qtpl:2
package mil82

//line view.qtpl:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view.qtpl:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view.qtpl:2
func (nd reportNode) StreamView(qw422016 *qt422016.Writer) {
	//line view.qtpl:2
	qw422016.N().S(`
    `)
	//line view.qtpl:3
	if nd.Table != nil {
		//line view.qtpl:3
		qw422016.N().S(`
        `)
		//line view.qtpl:4
		nd.Table.StreamView(qw422016)
		//line view.qtpl:4
		qw422016.N().S(`
    `)
		//line view.qtpl:5
	} else {
		//line view.qtpl:5
		qw422016.N().S(`

        `)
		//line view.qtpl:7
		if nd.Tree.Level == 0 {
			//line view.qtpl:7
			qw422016.N().S(`
            <h3 class="level0-caption"  >
                `)
			//line view.qtpl:9
			qw422016.E().S(nd.Tree.Title)
			//line view.qtpl:9
			qw422016.N().S(`
            </h3>
        `)
			//line view.qtpl:11
		} else {
			//line view.qtpl:11
			qw422016.N().S(`
            <h4 class="level1-caption"  >
                `)
			//line view.qtpl:13
			qw422016.E().S(nd.Tree.Title)
			//line view.qtpl:13
			qw422016.N().S(`
            </h4>
        `)
			//line view.qtpl:15
		}
		//line view.qtpl:15
		qw422016.N().S(`

        `)
		//line view.qtpl:17
		for _, nd2 := range nd.Tree.Nodes {
			//line view.qtpl:17
			qw422016.N().S(`
            `)
			//line view.qtpl:18
			nd2.StreamView(qw422016)
			//line view.qtpl:18
			qw422016.N().S(`
        `)
			//line view.qtpl:19
		}
		//line view.qtpl:19
		qw422016.N().S(`

    `)
		//line view.qtpl:21
	}
	//line view.qtpl:21
	qw422016.N().S(`
`)
//line view.qtpl:22
}

//line view.qtpl:22
func (nd reportNode) WriteView(qq422016 qtio422016.Writer) {
	//line view.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:22
	nd.StreamView(qw422016)
	//line view.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:22
}

//line view.qtpl:22
func (nd reportNode) View() string {
	//line view.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:22
	nd.WriteView(qb422016)
	//line view.qtpl:22
	qs422016 := string(qb422016.B)
	//line view.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:22
	return qs422016
//line view.qtpl:22
}

//line view.qtpl:24
func StreamViewParty(qw422016 *qt422016.Writer, partyID int64) {
	//line view.qtpl:24
	qw422016.N().S(`
    `)
	//line view.qtpl:25
	nds := reportParty(partyID)

	//line view.qtpl:25
	qw422016.N().S(`

    <html>
    <head>
        <title>МИЛ-82. Партия `)
	//line view.qtpl:29
	qw422016.N().D(int(partyID))
	//line view.qtpl:29
	qw422016.N().S(`. </title>
        <link rel="stylesheet" type="text/css" href="assets/data.css">
    </head>
    <body>
        `)
	//line view.qtpl:33
	for _, nd := range nds {
		//line view.qtpl:33
		qw422016.N().S(`
            `)
		//line view.qtpl:34
		nd.StreamView(qw422016)
		//line view.qtpl:34
		qw422016.N().S(`
        `)
		//line view.qtpl:35
	}
	//line view.qtpl:35
	qw422016.N().S(`
    </body>
    </html>
`)
//line view.qtpl:38
}

//line view.qtpl:38
func WriteViewParty(qq422016 qtio422016.Writer, partyID int64) {
	//line view.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:38
	StreamViewParty(qw422016, partyID)
	//line view.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:38
}

//line view.qtpl:38
func ViewParty(partyID int64) string {
	//line view.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:38
	WriteViewParty(qb422016, partyID)
	//line view.qtpl:38
	qs422016 := string(qb422016.B)
	//line view.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:38
	return qs422016
//line view.qtpl:38
}

//line view.qtpl:40
func (x reportTable) StreamView(qw422016 *qt422016.Writer) {
	//line view.qtpl:40
	qw422016.N().S(`
    <table class="tab2">
        <caption>`)
	//line view.qtpl:42
	qw422016.E().S(varName[x.Var])
	//line view.qtpl:42
	qw422016.N().S(`</caption>
        <thead>
            <tr>
                <th>Адрес</th>
                <th>Сер.№</th>
                `)
	//line view.qtpl:47
	for _, gas := range x.Gases {
		//line view.qtpl:47
		qw422016.N().S(`
                    <th>ПГС`)
		//line view.qtpl:48
		qw422016.N().D(int(gas))
		//line view.qtpl:48
		qw422016.N().S(`</th>
                `)
		//line view.qtpl:49
	}
	//line view.qtpl:49
	qw422016.N().S(`
            </tr>
        </thead>
        <tbody>
            `)
	//line view.qtpl:53
	for _, r := range x.Rows {
		//line view.qtpl:53
		qw422016.N().S(`
             <tr>
                <th>`)
		//line view.qtpl:55
		qw422016.N().D(int(r.Addr))
		//line view.qtpl:55
		qw422016.N().S(` </th>
                <td>`)
		//line view.qtpl:56
		qw422016.N().D(r.Serial)
		//line view.qtpl:56
		qw422016.N().S(` </td>
                `)
		//line view.qtpl:57
		for _, pV := range r.Values {
			//line view.qtpl:57
			qw422016.N().S(`
                    <td>
                        `)
			//line view.qtpl:59
			if pV != nil {
				//line view.qtpl:59
				qw422016.N().S(`
                            `)
				//line view.qtpl:60
				qw422016.N().F(*pV)
				//line view.qtpl:60
				qw422016.N().S(`
                        `)
				//line view.qtpl:61
			}
			//line view.qtpl:61
			qw422016.N().S(`
                    </td>
                `)
			//line view.qtpl:63
		}
		//line view.qtpl:63
		qw422016.N().S(`
             </tr>
             `)
		//line view.qtpl:65
	}
	//line view.qtpl:65
	qw422016.N().S(`
        </tbody>
    </table>
`)
//line view.qtpl:68
}

//line view.qtpl:68
func (x reportTable) WriteView(qq422016 qtio422016.Writer) {
	//line view.qtpl:68
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:68
	x.StreamView(qw422016)
	//line view.qtpl:68
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:68
}

//line view.qtpl:68
func (x reportTable) View() string {
	//line view.qtpl:68
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:68
	x.WriteView(qb422016)
	//line view.qtpl:68
	qs422016 := string(qb422016.B)
	//line view.qtpl:68
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:68
	return qs422016
//line view.qtpl:68
}
