// This file is automatically generated by qtc from "view.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line view.qtpl:1
package mil82

//line view.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view.qtpl:1
func streamviewReportTables(qw422016 *qt422016.Writer, reportTables []reportTable) {
	//line view.qtpl:1
	qw422016.N().S(`
    `)
	//line view.qtpl:2
	for _, t := range reportTables {
		//line view.qtpl:2
		qw422016.N().S(`
        `)
		//line view.qtpl:3
		t.StreamView(qw422016)
		//line view.qtpl:3
		qw422016.N().S(`
    `)
		//line view.qtpl:4
	}
	//line view.qtpl:4
	qw422016.N().S(`
`)
//line view.qtpl:5
}

//line view.qtpl:5
func writeviewReportTables(qq422016 qtio422016.Writer, reportTables []reportTable) {
	//line view.qtpl:5
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:5
	streamviewReportTables(qw422016, reportTables)
	//line view.qtpl:5
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:5
}

//line view.qtpl:5
func viewReportTables(reportTables []reportTable) string {
	//line view.qtpl:5
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:5
	writeviewReportTables(qb422016, reportTables)
	//line view.qtpl:5
	qs422016 := string(qb422016.B)
	//line view.qtpl:5
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:5
	return qs422016
//line view.qtpl:5
}

//line view.qtpl:7
func (nd reportNode) StreamView(qw422016 *qt422016.Writer, titlePrefix string) {
	//line view.qtpl:7
	qw422016.N().S(`
    `)
	//line view.qtpl:8
	streamviewReportTables(qw422016, nd.Tables(titlePrefix))
	//line view.qtpl:8
	qw422016.N().S(`
`)
//line view.qtpl:9
}

//line view.qtpl:9
func (nd reportNode) WriteView(qq422016 qtio422016.Writer, titlePrefix string) {
	//line view.qtpl:9
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:9
	nd.StreamView(qw422016, titlePrefix)
	//line view.qtpl:9
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:9
}

//line view.qtpl:9
func (nd reportNode) View(titlePrefix string) string {
	//line view.qtpl:9
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:9
	nd.WriteView(qb422016, titlePrefix)
	//line view.qtpl:9
	qs422016 := string(qb422016.B)
	//line view.qtpl:9
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:9
	return qs422016
//line view.qtpl:9
}

//line view.qtpl:11
func StreamViewParty(qw422016 *qt422016.Writer, partyID int64) {
	//line view.qtpl:11
	qw422016.N().S(`
    `)
	//line view.qtpl:12
	streambeginHtml(qw422016)
	//line view.qtpl:12
	qw422016.N().S(`
    `)
	//line view.qtpl:13
	for _, nd := range reportParty(partyID) {
		//line view.qtpl:13
		qw422016.N().S(`
        `)
		//line view.qtpl:14
		nd.StreamView(qw422016, "")
		//line view.qtpl:14
		qw422016.N().S(`
    `)
		//line view.qtpl:15
	}
	//line view.qtpl:15
	qw422016.N().S(`
    `)
	//line view.qtpl:16
	streamendHtml(qw422016)
	//line view.qtpl:16
	qw422016.N().S(`
`)
//line view.qtpl:17
}

//line view.qtpl:17
func WriteViewParty(qq422016 qtio422016.Writer, partyID int64) {
	//line view.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:17
	StreamViewParty(qw422016, partyID)
	//line view.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:17
}

//line view.qtpl:17
func ViewParty(partyID int64) string {
	//line view.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:17
	WriteViewParty(qb422016, partyID)
	//line view.qtpl:17
	qs422016 := string(qb422016.B)
	//line view.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:17
	return qs422016
//line view.qtpl:17
}

//line view.qtpl:19
func (x reportTable) StreamView(qw422016 *qt422016.Writer) {
	//line view.qtpl:19
	qw422016.N().S(`
    <h3>`)
	//line view.qtpl:20
	qw422016.E().S(x.Title)
	//line view.qtpl:20
	qw422016.N().S(`</h3>
    <table class="tab2">
        <thead>
            <tr>
                <th>Адрес</th>
                <th>Сер.№</th>
                `)
	//line view.qtpl:26
	for _, gas := range x.Gases {
		//line view.qtpl:26
		qw422016.N().S(`
                    <th>ПГС`)
		//line view.qtpl:27
		qw422016.N().D(int(gas))
		//line view.qtpl:27
		qw422016.N().S(`</th>
                `)
		//line view.qtpl:28
	}
	//line view.qtpl:28
	qw422016.N().S(`
            </tr>
        </thead>
        <tbody>
            `)
	//line view.qtpl:32
	for _, r := range x.Rows {
		//line view.qtpl:32
		qw422016.N().S(`
             <tr>
                <th style="text-align:left;" >`)
		//line view.qtpl:34
		qw422016.N().D(int(r.Addr))
		//line view.qtpl:34
		qw422016.N().S(` </th>
                <td style="text-align:left;" >`)
		//line view.qtpl:35
		qw422016.N().D(r.Serial)
		//line view.qtpl:35
		qw422016.N().S(` </td>
                `)
		//line view.qtpl:36
		for _, pV := range r.Values {
			//line view.qtpl:36
			qw422016.N().S(`
                    <td style="text-align:left;">
                        `)
			//line view.qtpl:38
			if pV != nil {
				//line view.qtpl:38
				qw422016.N().S(`
                            `)
				//line view.qtpl:39
				qw422016.N().F(*pV)
				//line view.qtpl:39
				qw422016.N().S(`
                        `)
				//line view.qtpl:40
			}
			//line view.qtpl:40
			qw422016.N().S(`
                    </td>
                `)
			//line view.qtpl:42
		}
		//line view.qtpl:42
		qw422016.N().S(`
             </tr>
             `)
		//line view.qtpl:44
	}
	//line view.qtpl:44
	qw422016.N().S(`
        </tbody>
    </table>
`)
//line view.qtpl:47
}

//line view.qtpl:47
func (x reportTable) WriteView(qq422016 qtio422016.Writer) {
	//line view.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:47
	x.StreamView(qw422016)
	//line view.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:47
}

//line view.qtpl:47
func (x reportTable) View() string {
	//line view.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:47
	x.WriteView(qb422016)
	//line view.qtpl:47
	qs422016 := string(qb422016.B)
	//line view.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:47
	return qs422016
//line view.qtpl:47
}

//line view.qtpl:49
func streambeginHtml(qw422016 *qt422016.Writer) {
	//line view.qtpl:49
	qw422016.N().S(`
    <html>
    	<head>
            <title>Партия</title>
            <link rel="stylesheet" type="text/css" href="assets/data.css">
        </head>
        <body>
`)
//line view.qtpl:56
}

//line view.qtpl:56
func writebeginHtml(qq422016 qtio422016.Writer) {
	//line view.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:56
	streambeginHtml(qw422016)
	//line view.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:56
}

//line view.qtpl:56
func beginHtml() string {
	//line view.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:56
	writebeginHtml(qb422016)
	//line view.qtpl:56
	qs422016 := string(qb422016.B)
	//line view.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:56
	return qs422016
//line view.qtpl:56
}

//line view.qtpl:58
func streamendHtml(qw422016 *qt422016.Writer) {
	//line view.qtpl:58
	qw422016.N().S(`
    </body>
    </html>
`)
//line view.qtpl:61
}

//line view.qtpl:61
func writeendHtml(qq422016 qtio422016.Writer) {
	//line view.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line view.qtpl:61
	streamendHtml(qw422016)
	//line view.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:61
}

//line view.qtpl:61
func endHtml() string {
	//line view.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
	//line view.qtpl:61
	writeendHtml(qb422016)
	//line view.qtpl:61
	qs422016 := string(qb422016.B)
	//line view.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
	//line view.qtpl:61
	return qs422016
//line view.qtpl:61
}
