// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package data

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type productTestErrorTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *productTestErrorTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("product_test_error").
func (v *productTestErrorTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *productTestErrorTableType) Columns() []string {
	return []string{"product_test_error_id", "product_id", "test_error_point", "gas_point", "value"}
}

// NewStruct makes a new struct for that view or table.
func (v *productTestErrorTableType) NewStruct() reform.Struct {
	return new(ProductTestError)
}

// NewRecord makes a new record for that table.
func (v *productTestErrorTableType) NewRecord() reform.Record {
	return new(ProductTestError)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *productTestErrorTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ProductTestErrorTable represents product_test_error view or table in SQL database.
var ProductTestErrorTable = &productTestErrorTableType{
	s: parse.StructInfo{Type: "ProductTestError", SQLSchema: "", SQLName: "product_test_error", Fields: []parse.FieldInfo{{Name: "ProductTestErrorID", Type: "int64", Column: "product_test_error_id"}, {Name: "ProductID", Type: "int64", Column: "product_id"}, {Name: "TestErrorPoint", Type: "string", Column: "test_error_point"}, {Name: "GasPoint", Type: "int64", Column: "gas_point"}, {Name: "Value", Type: "float64", Column: "value"}}, PKFieldIndex: 0},
	z: new(ProductTestError).Values(),
}

// String returns a string representation of this struct or record.
func (s ProductTestError) String() string {
	res := make([]string, 5)
	res[0] = "ProductTestErrorID: " + reform.Inspect(s.ProductTestErrorID, true)
	res[1] = "ProductID: " + reform.Inspect(s.ProductID, true)
	res[2] = "TestErrorPoint: " + reform.Inspect(s.TestErrorPoint, true)
	res[3] = "GasPoint: " + reform.Inspect(s.GasPoint, true)
	res[4] = "Value: " + reform.Inspect(s.Value, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *ProductTestError) Values() []interface{} {
	return []interface{}{
		s.ProductTestErrorID,
		s.ProductID,
		s.TestErrorPoint,
		s.GasPoint,
		s.Value,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *ProductTestError) Pointers() []interface{} {
	return []interface{}{
		&s.ProductTestErrorID,
		&s.ProductID,
		&s.TestErrorPoint,
		&s.GasPoint,
		&s.Value,
	}
}

// View returns View object for that struct.
func (s *ProductTestError) View() reform.View {
	return ProductTestErrorTable
}

// Table returns Table object for that record.
func (s *ProductTestError) Table() reform.Table {
	return ProductTestErrorTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *ProductTestError) PKValue() interface{} {
	return s.ProductTestErrorID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *ProductTestError) PKPointer() interface{} {
	return &s.ProductTestErrorID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *ProductTestError) HasPK() bool {
	return s.ProductTestErrorID != ProductTestErrorTable.z[ProductTestErrorTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *ProductTestError) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ProductTestErrorID = int64(i64)
	} else {
		s.ProductTestErrorID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = ProductTestErrorTable
	_ reform.Struct = (*ProductTestError)(nil)
	_ reform.Table  = ProductTestErrorTable
	_ reform.Record = (*ProductTestError)(nil)
	_ fmt.Stringer  = (*ProductTestError)(nil)
)

func init() {
	parse.AssertUpToDate(&ProductTestErrorTable.s, new(ProductTestError))
}
