// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package data

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type productCoefficientTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *productCoefficientTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("product_coefficient").
func (v *productCoefficientTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *productCoefficientTableType) Columns() []string {
	return []string{"product_coefficient_id", "product_id", "coefficient", "value"}
}

// NewStruct makes a new struct for that view or table.
func (v *productCoefficientTableType) NewStruct() reform.Struct {
	return new(ProductCoefficient)
}

// NewRecord makes a new record for that table.
func (v *productCoefficientTableType) NewRecord() reform.Record {
	return new(ProductCoefficient)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *productCoefficientTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ProductCoefficientTable represents product_coefficient view or table in SQL database.
var ProductCoefficientTable = &productCoefficientTableType{
	s: parse.StructInfo{Type: "ProductCoefficient", SQLSchema: "", SQLName: "product_coefficient", Fields: []parse.FieldInfo{{Name: "ProductCoefficientID", Type: "int64", Column: "product_coefficient_id"}, {Name: "ProductID", Type: "int64", Column: "product_id"}, {Name: "Coefficient", Type: "int64", Column: "coefficient"}, {Name: "Value", Type: "float64", Column: "value"}}, PKFieldIndex: 0},
	z: new(ProductCoefficient).Values(),
}

// String returns a string representation of this struct or record.
func (s ProductCoefficient) String() string {
	res := make([]string, 4)
	res[0] = "ProductCoefficientID: " + reform.Inspect(s.ProductCoefficientID, true)
	res[1] = "ProductID: " + reform.Inspect(s.ProductID, true)
	res[2] = "Coefficient: " + reform.Inspect(s.Coefficient, true)
	res[3] = "Value: " + reform.Inspect(s.Value, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *ProductCoefficient) Values() []interface{} {
	return []interface{}{
		s.ProductCoefficientID,
		s.ProductID,
		s.Coefficient,
		s.Value,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *ProductCoefficient) Pointers() []interface{} {
	return []interface{}{
		&s.ProductCoefficientID,
		&s.ProductID,
		&s.Coefficient,
		&s.Value,
	}
}

// View returns View object for that struct.
func (s *ProductCoefficient) View() reform.View {
	return ProductCoefficientTable
}

// Table returns Table object for that record.
func (s *ProductCoefficient) Table() reform.Table {
	return ProductCoefficientTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *ProductCoefficient) PKValue() interface{} {
	return s.ProductCoefficientID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *ProductCoefficient) PKPointer() interface{} {
	return &s.ProductCoefficientID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *ProductCoefficient) HasPK() bool {
	return s.ProductCoefficientID != ProductCoefficientTable.z[ProductCoefficientTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *ProductCoefficient) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ProductCoefficientID = int64(i64)
	} else {
		s.ProductCoefficientID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = ProductCoefficientTable
	_ reform.Struct = (*ProductCoefficient)(nil)
	_ reform.Table  = ProductCoefficientTable
	_ reform.Record = (*ProductCoefficient)(nil)
	_ fmt.Stringer  = (*ProductCoefficient)(nil)
)

func init() {
	parse.AssertUpToDate(&ProductCoefficientTable.s, new(ProductCoefficient))
}
