// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package data

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type productTempTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *productTempTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("product_temp").
func (v *productTempTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *productTempTableType) Columns() []string {
	return []string{"product_coefficient_id", "product_id", "gas_point", "temperature_point", "temperature", "value"}
}

// NewStruct makes a new struct for that view or table.
func (v *productTempTableType) NewStruct() reform.Struct {
	return new(ProductTemp)
}

// NewRecord makes a new record for that table.
func (v *productTempTableType) NewRecord() reform.Record {
	return new(ProductTemp)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *productTempTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ProductTempTable represents product_temp view or table in SQL database.
var ProductTempTable = &productTempTableType{
	s: parse.StructInfo{Type: "ProductTemp", SQLSchema: "", SQLName: "product_temp", Fields: []parse.FieldInfo{{Name: "ProductCoefficientID", Type: "int64", Column: "product_coefficient_id"}, {Name: "ProductID", Type: "int64", Column: "product_id"}, {Name: "GasPoint", Type: "int64", Column: "gas_point"}, {Name: "TemperaturePoint", Type: "int64", Column: "temperature_point"}, {Name: "Temperature", Type: "float64", Column: "temperature"}, {Name: "Value", Type: "float64", Column: "value"}}, PKFieldIndex: 0},
	z: new(ProductTemp).Values(),
}

// String returns a string representation of this struct or record.
func (s ProductTemp) String() string {
	res := make([]string, 6)
	res[0] = "ProductCoefficientID: " + reform.Inspect(s.ProductCoefficientID, true)
	res[1] = "ProductID: " + reform.Inspect(s.ProductID, true)
	res[2] = "GasPoint: " + reform.Inspect(s.GasPoint, true)
	res[3] = "TemperaturePoint: " + reform.Inspect(s.TemperaturePoint, true)
	res[4] = "Temperature: " + reform.Inspect(s.Temperature, true)
	res[5] = "Value: " + reform.Inspect(s.Value, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *ProductTemp) Values() []interface{} {
	return []interface{}{
		s.ProductCoefficientID,
		s.ProductID,
		s.GasPoint,
		s.TemperaturePoint,
		s.Temperature,
		s.Value,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *ProductTemp) Pointers() []interface{} {
	return []interface{}{
		&s.ProductCoefficientID,
		&s.ProductID,
		&s.GasPoint,
		&s.TemperaturePoint,
		&s.Temperature,
		&s.Value,
	}
}

// View returns View object for that struct.
func (s *ProductTemp) View() reform.View {
	return ProductTempTable
}

// Table returns Table object for that record.
func (s *ProductTemp) Table() reform.Table {
	return ProductTempTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *ProductTemp) PKValue() interface{} {
	return s.ProductCoefficientID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *ProductTemp) PKPointer() interface{} {
	return &s.ProductCoefficientID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *ProductTemp) HasPK() bool {
	return s.ProductCoefficientID != ProductTempTable.z[ProductTempTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *ProductTemp) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ProductCoefficientID = int64(i64)
	} else {
		s.ProductCoefficientID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = ProductTempTable
	_ reform.Struct = (*ProductTemp)(nil)
	_ reform.Table  = ProductTempTable
	_ reform.Record = (*ProductTemp)(nil)
	_ fmt.Stringer  = (*ProductTemp)(nil)
)

func init() {
	parse.AssertUpToDate(&ProductTempTable.s, new(ProductTemp))
}
