// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package data

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type workTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *workTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("work").
func (v *workTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *workTableType) Columns() []string {
	return []string{"work_id", "created_at", "name"}
}

// NewStruct makes a new struct for that view or table.
func (v *workTableType) NewStruct() reform.Struct {
	return new(Work)
}

// NewRecord makes a new record for that table.
func (v *workTableType) NewRecord() reform.Record {
	return new(Work)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *workTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// WorkTable represents work view or table in SQL database.
var WorkTable = &workTableType{
	s: parse.StructInfo{Type: "Work", SQLSchema: "", SQLName: "work", Fields: []parse.FieldInfo{{Name: "WorkID", Type: "int64", Column: "work_id"}, {Name: "CreatedAt", Type: "time.Time", Column: "created_at"}, {Name: "Name", Type: "string", Column: "name"}}, PKFieldIndex: 0},
	z: new(Work).Values(),
}

// String returns a string representation of this struct or record.
func (s Work) String() string {
	res := make([]string, 3)
	res[0] = "WorkID: " + reform.Inspect(s.WorkID, true)
	res[1] = "CreatedAt: " + reform.Inspect(s.CreatedAt, true)
	res[2] = "Name: " + reform.Inspect(s.Name, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Work) Values() []interface{} {
	return []interface{}{
		s.WorkID,
		s.CreatedAt,
		s.Name,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Work) Pointers() []interface{} {
	return []interface{}{
		&s.WorkID,
		&s.CreatedAt,
		&s.Name,
	}
}

// View returns View object for that struct.
func (s *Work) View() reform.View {
	return WorkTable
}

// Table returns Table object for that record.
func (s *Work) Table() reform.Table {
	return WorkTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Work) PKValue() interface{} {
	return s.WorkID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Work) PKPointer() interface{} {
	return &s.WorkID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Work) HasPK() bool {
	return s.WorkID != WorkTable.z[WorkTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Work) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.WorkID = int64(i64)
	} else {
		s.WorkID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = WorkTable
	_ reform.Struct = (*Work)(nil)
	_ reform.Table  = WorkTable
	_ reform.Record = (*Work)(nil)
	_ fmt.Stringer  = (*Work)(nil)
)

func init() {
	parse.AssertUpToDate(&WorkTable.s, new(Work))
}
